home:
  path: /home
  controller: App\Controller\HomeController::index

insert:
  path: /insert
  controller: App\Controller\HomeController::createPhoneManufacturer

addPhone:
  path: /v1/manufacturers/{id}/phones
  controller: App\Controller\V1\HomeController::addOnePhone

practiceAlg:
  path: /practiceAlg
  controller: App\Controller\V1\HomeController::practiceAlg