home:
  path: /home
  controller: App\Controller\HomeController::index

insert:
  path: /insert
  controller: App\Controller\HomeController::createPhoneManufacturer

showData:
  path: /onePhone
  controller: App\Controller\HomeController::getOnePhoneInfo
